name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.2.0

      - name: Build Debian package
        run: |
          DOCKER_BUILDKIT=1 docker build --target export . --output tmp --no-cache
          mv tmp/recovery.zip .
          rm -rf tmp

      - name: Upload Debian binary packages
        uses: actions/upload-artifact@v2
        with:
          path: recovery.zip
