name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.2.0

      - name: Build and extract recovery.zip
        run: |
          mkdir ${{ github.workspace }}/recovery-os
          cd ${{ github.workspace }}/recovery-os
          DOCKER_BUILDKIT=1 docker build --target export . --output tmp --no-cache
          mv ${{ github.workspace }}/recovery-os/tmp/recovery.zip ${{ github.workspace }}/recovery-os
          cd ${{ github.workspace }}
          rm -rf ${{ github.workspace }}/recovery-os/tmp
          cd ${{ github.workspace }}/recovery-os
          unzip recovery.zip
          rm recovery.zip

      - name: Upload recovery.zip contents
        uses: actions/upload-artifact@v2
        with:
          name: recovery
          path: ${{ github.workspace }}/recovery-os
