name: Create Draft GitHub Release

on:
  workflow_dispatch:
    branches:
      - master
    inputs:
      version:
        description: "What version do you want to release (no 'v')?"
        required: true
        default: ''

jobs:
  draft-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: master
          event: push
          name: "pi-topOS Recovery"
          path: .

      - name: Create Release
        uses: softprops/action-gh-release@v0.1.7
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          draft: true
          prerelease: false
          files: recovery.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
