name: Create Draft GitHub Release

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.2.0

      - name: Build and extract recovery.zip
        run: |
          DOCKER_BUILDKIT=1 docker build --target export . --output tmp --no-cache
          mv tmp/recovery.zip .
          rm -rf tmp

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "none"
          name: "Version Not Yet Set"
          draft: true
          prerelease: false
          files: recovery.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
