name: Create Draft GitHub Release

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  draft-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: master
          event: push
          name: "pi-topOS Recovery"
          path: .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "vX.Y.Z"
          name: "vX.Y.Z"
          draft: true
          prerelease: false
          files: recovery.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
